before_all do
  ensure_git_branch(
      branch: 'combined-dev'
  )
end

firebase_android_distribution_groups = "internal"
github_match_url = ENV['MATCH_REPO_URL']
ios_app_scheme = "BinBin"
appstore_provision_file = "match AppStore com.allmyne.rn"
adhoc_provision_file = "match AdHoc com.allmyne.rn"
code_signing_identity = "Apple Distribution: ALLMYNE.COM 21:21 Inc. (69P674CYLH)"
ios_commit_message = "[ci skip] Version Bump: #{ENV['VERSION_NUMBER']} (#{ENV['BUILD_NUMBER']})"
plist_file_path = "../ios/allmyneFeV2/Info.plist"
xcodeproj = File.absolute_path('../ios/ALLMYNE.xcodeproj')
xcworkspace = File.absolute_path('../ios/ALLMYNE.xcworkspace')

lane :increment_version do
  # latest_release = firebase_app_distribution_get_latest_release(
  #   app: ENV['FIREBASE_ANDROID_APP_ID'],
  #   service_credentials_file: File.absolute_path('../firebase-service-account.json'),
  # )
  # increment_version_code({ version_code: latest_release[:buildVersion].to_i + 1 })
  new_version_code = ENV['BUILD_NUMBER']
  increment_version_code({ version_code: new_version_code })
end

platform :android do
  desc "Android Production Build and Deploy to Firebase App Distribution"
  lane :firebase do 
      # increment_version_code(gradle_file_path: File.absolute_path('../android/app/build.gradle'))
      increment_version

      gradle(task: 'clean', project_dir: File.absolute_path('../android'))
      gradle(
          task: 'assemble',
          build_type: 'Release',
          project_dir: File.absolute_path('../android'),
          properties: {
              "android.injected.signing.store.file" => ENV['ANDROID_KEYSTORE_FILE'],
              "android.injected.signing.store.password" => ENV['ANDROID_KEYSTORE_PASSWORD'],
              "android.injected.signing.key.alias" => ENV['ANDROID_KEYSTORE_ALIAS'],
              "android.injected.signing.key.password" => ENV['ANDROID_KEYSTORE_PASSWORD']
          }
      )
      firebase_app_distribution(
          app: ENV['FIREBASE_ANDROID_APP_ID'],
          groups: firebase_android_distribution_groups,
          service_credentials_file: File.absolute_path('../firebase-service-account.json'),
          android_artifact_type: "APK"
      )
  end
end

def delete_temp_keychain(name)
delete_keychain(
  name: name
) if File.exist? File.expand_path("~/Library/Keychains/#{name}-db")
end

def create_temp_keychain(name, password)
create_keychain(
  name: name,
  password: password,
  unlock: false,
  timeout: 0
)
end

def ensure_temp_keychain(name, password)
delete_temp_keychain(name)
create_temp_keychain(name, password)
end

platform :ios do
desc "IOS Production Build and Deploy to TestFlight"
lane :test_flight do
    xcodes(
      version: "14.2",
      select_for_current_build_only: true
    )

    keychain_name = ENV['TEMP_KEYCHAIN_USER']
    keychain_password = ENV['TEMP_KEYCHAIN_PASSWORD']
    ensure_temp_keychain(keychain_name, keychain_password)

    increment_build_number(
      xcodeproj: xcodeproj,
      build_number: ENV['BUILD_NUMBER']
    )
    increment_version_number(
      xcodeproj: xcodeproj,
      version_number: ENV['VERSION_NUMBER']
    )

    cocoapods(
      clean_install: true,
      podfile: File.absolute_path('../ios/Podfile')
    )

    api_key = app_store_connect_api_key(
      key_id: ENV['APPLE_API_KEY_ID'],
      issuer_id: ENV['APPLE_ISSUER_ID'],
      key_filepath: File.absolute_path("../AppleApiKey.p8"),
      duration: 1200,
      in_house: false
    )

    sync_code_signing(
      type: "appstore",
      team_id: ENV['APPLE_TEAM_ID'],
      app_identifier: ENV['BUNDLE_ID'],
      git_basic_authorization: Base64.strict_encode64(ENV['GIT_PERSONAL_ACCESS_TOKEN']),
      keychain_name: keychain_name,
      keychain_password: keychain_password,
      git_url: github_match_url,
      api_key: api_key
    )

    update_project_provisioning(
      xcodeproj: xcodeproj,
      target_filter: ios_app_scheme,
      profile: ENV["sigh_#{ENV['BUNDLE_ID']}_appstore_profile-path"],
      build_configuration: "Release"
    )
    update_project_team(
      path: xcodeproj,
      teamid: ENV['APPLE_TEAM_ID']
    )

    build_app(
      export_team_id: ENV['APPLE_TEAM_ID'],
      configuration: "Release",
      workspace: xcworkspace,
      codesigning_identity: code_signing_identity,
      scheme: ios_app_scheme,
      export_method: "app-store",
      export_options: {
        provisioningProfiles: {  
          ENV['BUNDLE_ID'] => appstore_provision_file
        }
      }
    )

    upload_to_testflight(
      apple_id: ENV['APPLE_APP_ID'],
      app_identifier: ENV['BUNDLE_ID'],
      skip_waiting_for_build_processing: true,
      skip_submission: true,
      distribute_external: false,
      notify_external_testers: false
    )

    # version = get_version_number(xcodeproj: xcodeproj)
    # build = get_build_number(xcodeproj: xcodeproj)
    # clean_build_artifacts
    # git_commit(
    #   path: [File.absolute_path(plist_file_path)],
    #   message: ios_commit_message
    # )
    # push_to_git_remote

    delete_temp_keychain(keychain_name)
end
end
